### PR TITLE
Feature/tinzerillo/predictions

### PR DESCRIPTION
**Pull request by tinzerillo**
data side of the predictions feature

### CODE REVIEW

**Comment by mathcolo** [comment]
Superb!! 💯  Tested it and it works on my end! One question-- for insertion into predictionrecords can we use the internal ID of trips and stations instead of the MBTA ones? Should help with consistency and simplicity of application logic down the line 👍

**Comment by tinzerillo** [comment]
So much more work though :p

**Comment by tinzerillo** [comment]
But okaay

**Comment by mathcolo** [comment]
Should be 3-10 lines of code, you'll survive ;D

**Pull request merged**
