### PR TITLE
Working deployment environment!

### PR DESCRIPTION
**Pull request by mathcolo**
This PR contains
- Dockerfiles for pull and display
- docker-compose for doing it all
- Various other modifications

### CODE REVIEW

**Comment by mathcolo** [comment]
@kireledan Loooook I can docker! ;)

**Comment by tinzerillo** [comment]
This is awesome! Approved :)

**Comment by kireledan** [comment]
> avoid bugs by automatically running your tests

**Comment by mathcolo** [comment]
@kireledan Sorry I don't have a cluster to do that on ;)

**Pull request merged**
